controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_logout:
    path: /logout
    methods: GET
error_404:
    path: /{path}
    controller: App\Controller\ErrorController::notFound
    requirements:
        path: .*